---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  vars:
    test_config_name: molecule_test
    test_ipset_name: molecule_ipset

  tasks:
    - name: Verify dynamic-ipset CLI is working
      ansible.builtin.command: dynamic-ipset --version
      register: version_result
      changed_when: false

    - name: Display version
      ansible.builtin.debug:
        var: version_result.stdout

    - name: Check if IPv4 test ipset exists
      ansible.builtin.command: ipset list -n
      register: existing_sets
      changed_when: false

    - name: Create test ipset directly with ipset command
      ansible.builtin.command: >
        ipset create {{ test_ipset_name }} hash:net family inet
      register: create_result
      changed_when: create_result.rc == 0
      when: test_ipset_name not in existing_sets.stdout

    - name: Add IP entries to test set
      ansible.builtin.command: >
        ipset add {{ test_ipset_name }} {{ item }} -exist
      loop:
        - "192.168.1.0/24"
        - "10.0.0.0/8"
        - "172.16.0.0/12"
      register: add_result
      changed_when: false

    - name: List ipset entries
      ansible.builtin.command: ipset list {{ test_ipset_name }}
      register: list_result
      changed_when: false

    - name: Display ipset contents
      ansible.builtin.debug:
        var: list_result.stdout_lines

    - name: Create IPv6 test ipset
      ansible.builtin.command: >
        ipset create {{ test_ipset_name }}_v6 hash:net family inet6
      register: create_v6_result
      changed_when: create_v6_result.rc == 0
      when: (test_ipset_name ~ '_v6') not in existing_sets.stdout

    - name: Add IPv6 entries
      ansible.builtin.command: >
        ipset add {{ test_ipset_name }}_v6 {{ item }} -exist
      loop:
        - "2001:db8::/32"
        - "fd00::/8"
      register: add_v6_result
      changed_when: false

    - name: Check if dynamic-ipset config exists
      ansible.builtin.command: dynamic-ipset show {{ test_config_name }}
      register: config_check
      changed_when: false
      failed_when: false

    - name: Create dynamic-ipset configuration (requires URL)
      ansible.builtin.command: >
        dynamic-ipset create {{ test_config_name }}
        https://raw.githubusercontent.com/stamparm/ipsum/master/levels/3.txt
        --no-enable
      register: config_result
      changed_when: config_result.rc == 0
      when: config_check.rc != 0

    - name: Show dynamic-ipset configuration
      ansible.builtin.command: dynamic-ipset show
      register: show_result
      changed_when: false

    - name: Display configuration
      ansible.builtin.debug:
        var: show_result.stdout_lines
