---
- name: Verify
  hosts: all
  become: true
  gather_facts: true

  vars:
    test_ipset_name: molecule_ipset

  tasks:
    - name: Check dynamic-ipset binary exists
      ansible.builtin.stat:
        path: /usr/bin/dynamic-ipset
      register: binary_stat

    - name: Verify dynamic-ipset binary is present
      ansible.builtin.assert:
        that:
          - binary_stat.stat.exists
          - binary_stat.stat.executable
        fail_msg: "dynamic-ipset binary not found or not executable"
        success_msg: "dynamic-ipset binary is present and executable"

    - name: Check dynamic-ipset version
      ansible.builtin.command: dynamic-ipset --version
      register: version_result
      changed_when: false

    - name: Verify version command works
      ansible.builtin.assert:
        that:
          - version_result.rc == 0
        fail_msg: "dynamic-ipset --version failed"
        success_msg: "dynamic-ipset version: {{ version_result.stdout }}"

    - name: Check ipset is available
      ansible.builtin.command: ipset --version
      register: ipset_version
      changed_when: false

    - name: Verify ipset is installed
      ansible.builtin.assert:
        that:
          - ipset_version.rc == 0
        fail_msg: "ipset is not available"
        success_msg: "ipset is available: {{ ipset_version.stdout }}"

    - name: List all ipsets
      ansible.builtin.command: ipset list -n
      register: ipset_list
      changed_when: false

    - name: Verify IPv4 test set exists
      ansible.builtin.assert:
        that:
          - test_ipset_name in ipset_list.stdout
        fail_msg: "IPv4 test set '{{ test_ipset_name }}' not found"
        success_msg: "IPv4 test set '{{ test_ipset_name }}' exists"

    - name: Verify IPv6 test set exists
      ansible.builtin.assert:
        that:
          - (test_ipset_name ~ '_v6') in ipset_list.stdout
        fail_msg: "IPv6 test set '{{ test_ipset_name }}_v6' not found"
        success_msg: "IPv6 test set '{{ test_ipset_name }}_v6' exists"

    - name: Get IPv4 set entries
      ansible.builtin.command: ipset list {{ test_ipset_name }}
      register: v4_entries
      changed_when: false

    - name: Verify IPv4 entries are present
      ansible.builtin.assert:
        that:
          - "'192.168.1.0/24' in v4_entries.stdout"
          - "'10.0.0.0/8' in v4_entries.stdout"
          - "'172.16.0.0/12' in v4_entries.stdout"
        fail_msg: "IPv4 entries not found in set"
        success_msg: "All IPv4 entries present in set"

    - name: Get IPv6 set entries
      ansible.builtin.command: ipset list {{ test_ipset_name }}_v6
      register: v6_entries
      changed_when: false

    - name: Verify IPv6 entries are present
      ansible.builtin.assert:
        that:
          - "'2001:db8::/32' in v6_entries.stdout"
          - "'fd00::/8' in v6_entries.stdout"
        fail_msg: "IPv6 entries not found in set"
        success_msg: "All IPv6 entries present in set"

    - name: Test ipset atomic swap functionality
      block:
        - name: Create temporary set for swap test
          ansible.builtin.command: ipset create swap_test hash:net family inet

        - name: Add entry to swap test set
          ansible.builtin.command: ipset add swap_test 1.1.1.0/24

        - name: Swap sets
          ansible.builtin.command: ipset swap swap_test {{ test_ipset_name }}

        - name: Verify swap worked - original set should have new entry
          ansible.builtin.command: ipset list {{ test_ipset_name }}
          register: swapped_result

        - name: Assert swap was successful
          ansible.builtin.assert:
            that:
              - "'1.1.1.0/24' in swapped_result.stdout"
            fail_msg: "Atomic swap failed"
            success_msg: "Atomic swap successful"

    - name: Clean up test sets
      block:
        - name: Destroy IPv4 test set
          ansible.builtin.command: ipset destroy {{ test_ipset_name }}
          register: destroy_v4

        - name: Destroy IPv6 test set
          ansible.builtin.command: ipset destroy {{ test_ipset_name }}_v6
          register: destroy_v6

        - name: Destroy swap test set
          ansible.builtin.command: ipset destroy swap_test
          ignore_errors: true

        - name: Verify sets are destroyed
          ansible.builtin.command: ipset list -n
          register: final_list
          changed_when: false

        - name: Assert sets are gone
          ansible.builtin.assert:
            that:
              - test_ipset_name not in final_list.stdout
            fail_msg: "Test sets were not properly destroyed"
            success_msg: "Test sets successfully destroyed"
