#!/bin/sh
set -e

case "$1" in
    configure)
        # Reload systemd to pick up new unit files
        if [ -d /run/systemd/system ]; then
            systemctl daemon-reload || true
        fi
        ;;
    abort-upgrade|abort-remove|abort-deconfigure)
        ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
